# Generated by Django 2.1 on 2018-08-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=200)),
                ('friendly_name', models.CharField(max_length=200)),
                ('last_changed', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ha_integration.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('example', models.CharField(blank=True, max_length=200, null=True)),
                ('values', models.CharField(blank=True, max_length=200, null=True)),
                ('return_routes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=200)),
                ('friendly_name', models.CharField(max_length=200)),
                ('brightness', models.CharField(max_length=200)),
                ('hs_color', models.CharField(max_length=200)),
                ('rgb_color', models.CharField(max_length=200)),
                ('supported_features', models.CharField(max_length=200)),
                ('white_value', models.CharField(max_length=200)),
                ('xy_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ha_integration.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ha_integration.Service'),
        ),
    ]
