# Generated by Django 2.1 on 2018-08-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ha_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('new_state', models.TextField(blank=True, null=True)),
                ('old_state', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='last_changed',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='state',
        ),
        migrations.AddField(
            model_name='entity',
            name='current_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statechange',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ha_integration.Entity'),
        ),
    ]
