# Generated by Django 2.1 on 2018-08-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ha_integration', '0003_statechange_attributes_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ha_integration.Entity')),
            ],
        ),
        migrations.DeleteModel(
            name='Light',
        ),
        migrations.RemoveField(
            model_name='statechange',
            name='attributes_json',
        ),
        migrations.RemoveField(
            model_name='statechange',
            name='old_state',
        ),
    ]
