# Generated by Django 2.1 on 2018-08-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha_integration', '0004_auto_20180828_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statechange',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='current_state',
        ),
        migrations.DeleteModel(
            name='StateChange',
        ),
    ]
