# Generated by Django 2.1 on 2018-08-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha_integration', '0005_auto_20180828_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_new_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_old_state',
            field=models.BooleanField(default=False),
        ),
    ]
